/**
 * POS Types Index
 *
 * Re-exports shared types + POS-specific types.
 *
 * Usage:
 *   import type { Order, PaymentData, TableWithStatus } from '@/pos/types';
 */

// Re-export all shared types
export type {
    User,
    UserRole,
    Restaurant,
    Zone,
    Table,
    TableStatus,
    TableShape,
    Order,
    OrderStatus,
    OrderType,
    PaymentMethod,
    PaymentStatus,
    OrderSource,
    OrderItem,
    OrderItemStatus,
    OrderItemModifier,
    Category,
    Dish,
    ModifierGroup,
    Modifier,
    PriceList,
    PriceListItem,
    StopListItem,
    Customer,
    LoyaltyLevel,
    Promotion,
    PromoCode,
    GiftCertificate,
    CashShift,
    ShiftStatus,
    CashOperation,
    CashOperationType,
    Reservation,
    ReservationStatus,
    DeliveryOrder,
    DeliveryStatus,
    DeliveryProblem,
    DeliveryZone,
    Ingredient,
    Warehouse,
    InventoryMovement,
    Invoice,
    InvoiceItem,
    InventoryCheck,
    InventoryCheckItem,
    BarOrder,
    BarOrderStatus,
    BarOrderItem,
    BarStation,
    BarCounts,
    WriteOff,
    Notification,
    NotificationType,
    WorkSession,
    ApiResponse,
    ApiErrorResponse,
    PaginatedResponse,
    PaginationMeta,
    LoginResponse,
    MeResponse,
    ApiMethod,
    RequestConfig,
    ApiError,
} from '@/shared/types';

// POS-specific types
export type {
    PosSession,
    PosLimits,
    PosUser,
    FloorPlan,
    TableWithStatus,
    TableContextAction,
    ShiftReport,
    ShiftSummary,
    OpenShiftData,
    CloseShiftData,
    PaymentData,
    SplitPaymentData,
    CreateOrderData,
    CreateOrderItem,
    OrderDiscount,
    CustomerSearchResult,
    CustomerFormData,
    StopListEntry,
    DeliveryFilters,
    DeliveryStats,
    BarPanelData,
    PosTab,
    ToastMessage,
    ConfirmDialogOptions,
} from './pos';
